config/routes.rb
Rails.application.routes.draw do
  # root 'orders#new'
  resources :orders, only: [:new, :create]
  devise_for :users
  root 'home#index'
  get 'home/private'
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :email_send

  belongs_to :user
  belongs_to :event

  def email_send
    event = self.event
    event_admin = event.event_admin
    UserMailer.event_subscription(event_admin, event, user).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true, if: :in_the_futur
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }, if: :is_multiple_five?
  validates :title, presence: true, length: {in: 5..140}
  validates :description, presence: true, length: {in: 20..1000}
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :event_admin, class_name: "User"

  def in_the_futur
    errors.add(:start_date, "You can't create an even in the past.") unless start_date > DateTime.now
  end

  def is_multiple_five?
    errors.add(:duration, "Must be a multiple of five!") unless duration % 5 == 0
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # after_create :welcome_send

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  

  has_many :administrated_events, foreign_key: 'admin_id', class_name: 'Event'

  has_many :attendances
  has_many :events, through: :attendances

  

  # def welcome_send
  #   UserMailer.welcome_email(self).deliver_now
  # end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @events = Event.all
  end
  def action

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
@stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
# After the rescue, if the payment succeeded
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show]
  before_action :is_same_user?, only: [:show, :edit]

  def show
    @user = User.find(params[:id])
    @month_array = ["","JAN","FEV", "MAR", "AVR", "MAI", "JUN", "JUL", "AOU", "SEP", "OCT", "NOV", "DEC"]
  end

  def is_same_user?
    @user = User.find(params[:id])
    current_user == @user ? nil : (redirect_to root_path)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:first_name, :last_name, :description))
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end


  
end
#   before_action :set_user, only: %i[ show edit update destroy ]
# def action
# end  
#   # GET /users or /users.json
#   def index
#     @users = User.all
#   end

#   # GET /users/1 or /users/1.json
#   def show
#   end

#   # GET /users/new
#   def new
#     @user = User.new
#   end

#   # GET /users/1/edit
#   def edit
#   end

#   # POST /users or /users.json
#   def create
#     @user = User.new(user_params)

#       if @user.valid?
#         @user.save
#         UserNotifierMailer.send_signup_email(@user).deliver
#         redirect_to new_user_path
      
#         # format.html { redirect_to @user, notice: "User was successfully created." }
#         # format.json { render :show, status: :created, location: @user }

#       else
#         render "new"

#         # format.html { render :new, status: :unprocessable_entity }
#         # format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
    
#   end

#   # PATCH/PUT /users/1 or /users/1.json
#   def update
#     respond_to do |format|
#       if @user.update(user_params)
#         format.html { redirect_to @user, notice: "User was successfully updated." }
#         format.json { render :show, status: :ok, location: @user }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /users/1 or /users/1.json
#   def destroy
#     @user.destroy
#     respond_to do |format|
#       format.html { redirect_to users_url, notice: "User was successfully destroyed." }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_user
#       @user = User.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def user_params
#       params.require(:user).permit(:username, :first_name, :last_name, :description, :email, :encrypted_password)
#     end
#end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/index.html.erb
<h1>Binevenue sur mon site </h1>
<p>
<%if user_signed_in?%>

<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<%else%>
<%=link_to 'Se connecter',new_user_session_path%>
<%end%>
<%=link_to 'paiement',new_order_path%>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbritetest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert%></p>
  <%= yield%>
    <p>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<%= form_tag orders_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>